# Human one-liners for chart headers. Keyed by metric id; missing ids fall back
# to the metric title.
DESCRIPTIONS = {
    "blocks_hourly": "Blocks discovered per hour. Early chain shows sparse, irregular production.",
    "blocks_daily": "Blocks discovered per day. Expect ~144/day once mining stabilizes.",
    "blocks_weekly": "Blocks discovered per week (Monday start). Smooths daily variance.",
    "avg_block_size_daily": "Mean serialized block size per day in bytes.",
    "avg_block_size_weekly": "Count-weighted mean block size per week. Never an avg-of-avgs.",
    "avg_block_interval_daily": "Mean seconds between consecutive blocks per day. Target 600s.",
    "tx_count_hourly": "Non-coinbase transactions confirmed per hour.",
    "tx_count_daily": "Non-coinbase transactions confirmed per day.",
    "fees_hourly": "Total transaction fees paid per hour, in BTC.",
    "fees_daily": "Total transaction fees paid per day, in BTC.",
    "fees_weekly": "Total transaction fees paid per week, in BTC.",
    "feerate_median_daily": "Median fee rate per day in sat/vB. What a typical urgent tx paid.",
    "large_tx_hourly": "Transactions moving over 10 BTC per hour. Whale-activity proxy.",
    "hashrate_daily": "Estimated network hashrate per day from difficulty. Assumes 600s blocks.",
    "difficulty_daily": "Mean mining difficulty per day. Retargets every 2016 blocks.",
    "reward_daily": "New coins issued in coinbases per day, in BTC (subsidy only).",
    "active_addresses_hourly": "Distinct addresses seen in outputs per hour.",
    "active_addresses_daily": "Distinct addresses seen in outputs per day.",
    "realized_cap_daily": "Sum of coins valued at the price they last moved, in USD.",
    "realized_cap_weekly": "End-of-week realized capitalization, in USD.",
    "mvrv_daily": "Market value / realized value. Overbought when high, oversold when low.",
    "nupl_daily": "Net unrealized profit/loss as a share of market cap.",
    "sopr_daily": "Spent output profit ratio. Above 1 means coins moved at a profit.",
    "puell_daily": "Daily issuance value / its yearly average. Miner stress gauge.",
    "hodl_1y_plus_daily": "Coins unmoved for 1 year or more, in BTC.",
    "hodl_1y_plus_weekly": "End-of-week supply held 1 year or more, in BTC.",
    "hodl_5y_plus_daily": "Coins unmoved for 5 years or more, in BTC. True long-term holders.",
    "transfer_volume_daily": "Total value moved onchain per day, in BTC (excludes coinbases).",
    "nvt_daily": "Network value / transfer volume. High readings mean expensive chain usage.",
    "price_close_daily": "Daily BTC close price in USD (Binance).",
    "price_close_hourly": "Hourly BTC close price in USD (Binance).",
    "block_stats_daily": "Blocks discovered per day (legacy alias).",
    "tx_volume_hourly": "Non-coinbase transactions per hour (legacy alias).",
    "address_activity_daily": "Distinct active addresses per day (legacy alias).",
}
