# Metrics catalog v2 — every entry reads ONLY pre-aggregated MVs, marts, or
# price tables. NEVER base tables (bitcoin.blocks_v2 / transactions_v2 / ...).
#
# State layout (clickhouse/init/05_mvs.sql, 06_marts.sql, 03_schema_v2.sql):
# - *_hourly MVs hold aggregate STATES  -> query with -Merge combinators.
# - *_daily MVs hold -Merge FINALS       -> plain columns, NOT re-mergeable.
# - Weekly rollups over *_daily therefore use sums for flows, end-of-week
#   snapshots (argMax(..., day)) for stocks, and count-weighted averages
#   sum(avg_col*weight)/sum(weight) for averages. NEVER avg-of-avgs.
# - marts.* are ReplacingMergeTree(updated_at) -> argMax(col, updated_at).

METRICS = [
    # ---- family: network (mv_blocks_hourly/daily) ----
    {
        "id": "blocks_hourly",
        "title": "Blocks / hour",
        "category": "network",
        "unit": "blocks",
        "grain": "hourly",
        "sql": "SELECT hour, countMerge(block_count) FROM bitcoin.mv_blocks_hourly WHERE hour BETWEEN {from:DateTime} AND {to:DateTime} GROUP BY hour ORDER BY hour",
    },
    {
        "id": "blocks_daily",
        "title": "Blocks / day",
        "category": "network",
        "unit": "blocks",
        "grain": "daily",
        "sql": "SELECT day, blocks FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "blocks_weekly",
        "title": "Blocks / week",
        "category": "network",
        "unit": "blocks",
        "grain": "weekly",
        "sql": "SELECT toStartOfWeek(day), sum(blocks) FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY toStartOfWeek(day) ORDER BY toStartOfWeek(day)",
    },
    {
        "id": "avg_block_size_daily",
        "title": "Avg block size / day",
        "category": "network",
        "unit": "bytes",
        "grain": "daily",
        "sql": "SELECT day, avg_size FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "avg_block_size_weekly",
        "title": "Avg block size / week",
        "category": "network",
        "unit": "bytes",
        "grain": "weekly",
        "sql": "SELECT toStartOfWeek(day), sum(avg_size * blocks) / sum(blocks) FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY toStartOfWeek(day) ORDER BY toStartOfWeek(day)",
    },
    {
        "id": "avg_block_interval_daily",
        "title": "Avg block interval / day",
        "category": "network",
        "unit": "seconds",
        "grain": "daily",
        "sql": "SELECT day, avg_interval FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    # ---- family: fees (mv_tx_fee_hourly/daily) ----
    {
        "id": "tx_count_hourly",
        "title": "Transactions / hour",
        "category": "fees",
        "unit": "tx",
        "grain": "hourly",
        "sql": "SELECT hour, countMerge(tx_count) FROM bitcoin.mv_tx_fee_hourly WHERE hour BETWEEN {from:DateTime} AND {to:DateTime} GROUP BY hour ORDER BY hour",
    },
    {
        "id": "tx_count_daily",
        "title": "Transactions / day",
        "category": "fees",
        "unit": "tx",
        "grain": "daily",
        "sql": "SELECT day, tx_count FROM bitcoin.mv_tx_fee_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "fees_hourly",
        "title": "Total fees / hour",
        "category": "fees",
        "unit": "BTC",
        "grain": "hourly",
        "sql": "SELECT hour, sumMerge(fee_sum) / 1e8 FROM bitcoin.mv_tx_fee_hourly WHERE hour BETWEEN {from:DateTime} AND {to:DateTime} GROUP BY hour ORDER BY hour",
    },
    {
        "id": "fees_daily",
        "title": "Total fees / day",
        "category": "fees",
        "unit": "BTC",
        "grain": "daily",
        "sql": "SELECT day, fee_sum / 1e8 FROM bitcoin.mv_tx_fee_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "fees_weekly",
        "title": "Total fees / week",
        "category": "fees",
        "unit": "BTC",
        "grain": "weekly",
        "sql": "SELECT toStartOfWeek(day), sum(fee_sum) / 1e8 FROM bitcoin.mv_tx_fee_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY toStartOfWeek(day) ORDER BY toStartOfWeek(day)",
    },
    {
        "id": "feerate_median_daily",
        "title": "Median feerate / day",
        "category": "fees",
        "unit": "sat/vB",
        "grain": "daily",
        "sql": "SELECT day, feerate_median FROM bitcoin.mv_tx_fee_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "large_tx_hourly",
        "title": "Large transactions (>10 BTC) / hour",
        "category": "fees",
        "unit": "tx",
        "grain": "hourly",
        "sql": "SELECT hour, countMerge(large_tx_count) FROM bitcoin.mv_tx_fee_hourly WHERE hour BETWEEN {from:DateTime} AND {to:DateTime} GROUP BY hour ORDER BY hour",
    },
    # ---- family: mining (derived from mv_blocks_daily finals) ----
    {
        "id": "hashrate_daily",
        "title": "Est. hashrate / day",
        "category": "mining",
        "unit": "H/s",
        "grain": "daily",
        "sql": "SELECT day, avg_difficulty * 4294967296 / 600 FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "difficulty_daily",
        "title": "Difficulty / day",
        "category": "mining",
        "unit": "difficulty",
        "grain": "daily",
        "sql": "SELECT day, avg_difficulty FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "reward_daily",
        "title": "Block rewards / day",
        "category": "mining",
        "unit": "BTC",
        "grain": "daily",
        "sql": "SELECT day, reward_sum / 1e8 FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    # ---- family: addresses (mv_addr_hourly/daily) ----
    {
        "id": "active_addresses_hourly",
        "title": "Active addresses / hour",
        "category": "addresses",
        "unit": "addresses",
        "grain": "hourly",
        "sql": "SELECT hour, uniqMerge(active) FROM bitcoin.mv_addr_hourly WHERE hour BETWEEN {from:DateTime} AND {to:DateTime} GROUP BY hour ORDER BY hour",
    },
    {
        "id": "active_addresses_daily",
        "title": "Active addresses / day",
        "category": "addresses",
        "unit": "addresses",
        "grain": "daily",
        "sql": "SELECT day, active FROM bitcoin.mv_addr_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    # ---- family: valuation (marts.*) ----
    {
        "id": "realized_cap_daily",
        "title": "Realized cap / day",
        "category": "valuation",
        "unit": "USD",
        "grain": "daily",
        "sql": "SELECT day, argMax(realized_cap, updated_at) FROM marts.realized_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    {
        "id": "realized_cap_weekly",
        "title": "Realized cap / week (end-of-week)",
        "category": "valuation",
        "unit": "USD",
        "grain": "weekly",
        "sql": "SELECT toStartOfWeek(day), argMax(realized_cap, day) FROM marts.realized_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY toStartOfWeek(day) ORDER BY toStartOfWeek(day)",
    },
    {
        "id": "mvrv_daily",
        "title": "MVRV / day",
        "category": "valuation",
        "unit": "ratio",
        "grain": "daily",
        "sql": "SELECT day, argMax(mvrv, updated_at) FROM marts.mvrv_nupl_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    {
        "id": "nupl_daily",
        "title": "NUPL / day",
        "category": "valuation",
        "unit": "ratio",
        "grain": "daily",
        "sql": "SELECT day, argMax(nupl, updated_at) FROM marts.mvrv_nupl_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    # ---- family: profitability (marts.*) ----
    {
        "id": "sopr_daily",
        "title": "SOPR / day",
        "category": "profitability",
        "unit": "ratio",
        "grain": "daily",
        "sql": "SELECT day, argMax(sopr, updated_at) FROM marts.sopr_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    {
        "id": "puell_daily",
        "title": "Puell multiple / day",
        "category": "profitability",
        "unit": "ratio",
        "grain": "daily",
        "sql": "SELECT day, argMax(puell, updated_at) FROM marts.puell_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    # ---- family: supply / hodl (marts.hodl_daily, bands in sat) ----
    {
        "id": "hodl_1y_plus_daily",
        "title": "Supply held 1y+ / day",
        "category": "supply",
        "unit": "BTC",
        "grain": "daily",
        "sql": "SELECT day, (argMax(band_1y, updated_at) + argMax(band_2y, updated_at) + argMax(band_5y_plus, updated_at)) / 1e8 FROM marts.hodl_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    {
        "id": "hodl_1y_plus_weekly",
        "title": "Supply held 1y+ / week (end-of-week)",
        "category": "supply",
        "unit": "BTC",
        "grain": "weekly",
        "sql": "SELECT toStartOfWeek(day), argMax(band_1y + band_2y + band_5y_plus, day) / 1e8 FROM marts.hodl_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY toStartOfWeek(day) ORDER BY toStartOfWeek(day)",
    },
    {
        "id": "hodl_5y_plus_daily",
        "title": "Supply held 5y+ / day",
        "category": "supply",
        "unit": "BTC",
        "grain": "daily",
        "sql": "SELECT day, argMax(band_5y_plus, updated_at) / 1e8 FROM marts.hodl_daily WHERE day BETWEEN {from:Date} AND {to:Date} GROUP BY day ORDER BY day",
    },
    # ---- family: flow + price ----
    {
        "id": "transfer_volume_daily",
        "title": "Onchain transfer volume / day",
        "category": "flow",
        "unit": "BTC",
        "grain": "daily",
        "sql": "SELECT day, transfer_sum / 1e8 FROM bitcoin.mv_flow_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "nvt_daily",
        "title": "NVT / day (supply from cumulative rewards / transfer volume)",
        "category": "flow",
        "unit": "ratio",
        "grain": "daily",
        "sql": "SELECT day, supply_btc / nullIf(transfer_btc, 0) FROM (SELECT b.day AS day, sum(b.reward_btc) OVER (ORDER BY b.day ROWS UNBOUNDED PRECEDING) AS supply_btc, f.transfer_btc AS transfer_btc FROM (SELECT day, reward_sum / 1e8 AS reward_btc FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date}) AS b JOIN (SELECT day, transfer_sum / 1e8 AS transfer_btc FROM bitcoin.mv_flow_daily WHERE day BETWEEN {from:Date} AND {to:Date}) AS f ON b.day = f.day) ORDER BY day",
    },
    {
        "id": "price_close_daily",
        "title": "BTC close / day",
        "category": "price",
        "unit": "USD",
        "grain": "daily",
        "sql": "SELECT day, close FROM bitcoin.price_ohlc_daily WHERE symbol = 'BTCUSDT' AND day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "price_close_hourly",
        "title": "BTC close / hour",
        "category": "price",
        "unit": "USD",
        "grain": "hourly",
        "sql": "SELECT ts, close FROM bitcoin.price_ohlc_hourly WHERE symbol = 'BTCUSDT' AND ts BETWEEN {from:DateTime} AND {to:DateTime} ORDER BY ts",
    },
    # ---- legacy aliases (kept for existing API consumers + test_metrics.py) ----
    {
        "id": "block_stats_daily",
        "title": "Blocks / day",
        "category": "onchain",
        "unit": "blocks",
        "grain": "daily",
        "sql": "SELECT day, blocks FROM bitcoin.mv_blocks_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "tx_volume_hourly",
        "title": "TX volume / hour",
        "category": "onchain",
        "unit": "tx",
        "grain": "hourly",
        "sql": "SELECT hour, countMerge(tx_count) FROM bitcoin.mv_tx_fee_hourly WHERE hour BETWEEN {from:DateTime} AND {to:DateTime} GROUP BY hour ORDER BY hour",
    },
    {
        "id": "address_activity_daily",
        "title": "Active addresses / day",
        "category": "onchain",
        "unit": "addresses",
        "grain": "daily",
        "sql": "SELECT day, active FROM bitcoin.mv_addr_daily WHERE day BETWEEN {from:Date} AND {to:Date} ORDER BY day",
    },
    {
        "id": "price_btc_usd",
        "title": "BTC price (stub)",
        "category": "price",
        "unit": "USD",
        "grain": "none",
        "disabled": True,
    },
]
