ALTER TABLE bitcoin.blocks_v2 ADD PROJECTION IF NOT EXISTS p_height (SELECT * ORDER BY height) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.blocks_v2 ADD PROJECTION IF NOT EXISTS p_hash (SELECT hash, prev_hash, merkle_root, height, timestamp) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.transactions_v2 ADD PROJECTION IF NOT EXISTS p_block (SELECT * ORDER BY (block_height, txid)) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.transactions_v2 ADD PROJECTION IF NOT EXISTS p_txid (SELECT txid, block_height, timestamp, fee_sat) ORDER BY txid SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.transactions_v2 ADD PROJECTION IF NOT EXISTS p_fee (SELECT fee_rate_sat_vbyte, fee_sat, timestamp) ORDER BY fee_rate_sat_vbyte SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.outputs_v2 ADD PROJECTION IF NOT EXISTS p_addr_time (SELECT * ORDER BY (address, timestamp)) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.outputs_v2 ADD PROJECTION IF NOT EXISTS p_spend (SELECT spending_txid, spent_height, txid, output_index) ORDER BY spending_txid SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.outputs_v2 ADD PROJECTION IF NOT EXISTS p_value (SELECT value_sat, timestamp, address) ORDER BY value_sat SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.inputs_v2 ADD PROJECTION IF NOT EXISTS p_prev (SELECT * ORDER BY (prev_txid, prev_output_index)) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.inputs_v2 ADD PROJECTION IF NOT EXISTS p_block (SELECT * ORDER BY (block_height, txid)) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.addresses_v2 ADD PROJECTION IF NOT EXISTS p_seen (SELECT * ORDER BY (last_seen_time, bucket)) SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.addresses_v2 ADD PROJECTION IF NOT EXISTS p_balance (SELECT balance_sat, address, bucket) ORDER BY balance_sat SETTINGS compress_primary_key = 1;
ALTER TABLE bitcoin.blocks_v2 MATERIALIZE PROJECTION p_height;
ALTER TABLE bitcoin.blocks_v2 MATERIALIZE PROJECTION p_hash;
ALTER TABLE bitcoin.transactions_v2 MATERIALIZE PROJECTION p_block;
ALTER TABLE bitcoin.transactions_v2 MATERIALIZE PROJECTION p_txid;
ALTER TABLE bitcoin.transactions_v2 MATERIALIZE PROJECTION p_fee;
ALTER TABLE bitcoin.outputs_v2 MATERIALIZE PROJECTION p_addr_time;
ALTER TABLE bitcoin.outputs_v2 MATERIALIZE PROJECTION p_spend;
ALTER TABLE bitcoin.outputs_v2 MATERIALIZE PROJECTION p_value;
ALTER TABLE bitcoin.inputs_v2 MATERIALIZE PROJECTION p_prev;
ALTER TABLE bitcoin.inputs_v2 MATERIALIZE PROJECTION p_block;
ALTER TABLE bitcoin.addresses_v2 MATERIALIZE PROJECTION p_seen;
ALTER TABLE bitcoin.addresses_v2 MATERIALIZE PROJECTION p_balance;
